version: '3'
services:
  web:
    image: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "2024:2024"
    expose:
      - "2024"
    env_file:
      - .env
    
